{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "7039020a",
   "metadata": {},
   "outputs": [],
   "source": [
    "from PIL import ImageTk, Image, ImageDraw, ImageGrab\n",
    "import PIL\n",
    "from tkinter import *\n",
    "import tkinter as tk\n",
    "import cv2 as cv"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "id": "cf3daf60",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-57-f9d911dce305>\", line 24, in clear\n",
      "    ImageGrab.grab((10,10,10,10)).save('user_input.jpg')\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2172, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\site-packages\\PIL\\JpegImagePlugin.py\", line 784, in _save\n",
      "    ImageFile._save(im, fp, [(\"jpeg\", (0, 0) + im.size, 0, rawmode)], bufsize)\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\site-packages\\PIL\\ImageFile.py\", line 527, in _save\n",
      "    e.setimage(im.im, b)\n",
      "SystemError: tile cannot extend outside image\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-57-f9d911dce305>\", line 24, in clear\n",
      "    ImageGrab.grab((10,10,10,10)).save('user_input.jpg')\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2172, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\site-packages\\PIL\\JpegImagePlugin.py\", line 784, in _save\n",
      "    ImageFile._save(im, fp, [(\"jpeg\", (0, 0) + im.size, 0, rawmode)], bufsize)\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\site-packages\\PIL\\ImageFile.py\", line 527, in _save\n",
      "    e.setimage(im.im, b)\n",
      "SystemError: tile cannot extend outside image\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-57-f9d911dce305>\", line 24, in clear\n",
      "    ImageGrab.grab((10,10,10,10)).save('user_input.jpg')\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2172, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\site-packages\\PIL\\JpegImagePlugin.py\", line 784, in _save\n",
      "    ImageFile._save(im, fp, [(\"jpeg\", (0, 0) + im.size, 0, rawmode)], bufsize)\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\site-packages\\PIL\\ImageFile.py\", line 527, in _save\n",
      "    e.setimage(im.im, b)\n",
      "SystemError: tile cannot extend outside image\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-57-f9d911dce305>\", line 24, in clear\n",
      "    ImageGrab.grab((10,10,10,10)).save('user_input.jpg')\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2172, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\site-packages\\PIL\\JpegImagePlugin.py\", line 784, in _save\n",
      "    ImageFile._save(im, fp, [(\"jpeg\", (0, 0) + im.size, 0, rawmode)], bufsize)\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\site-packages\\PIL\\ImageFile.py\", line 527, in _save\n",
      "    e.setimage(im.im, b)\n",
      "SystemError: tile cannot extend outside image\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"<ipython-input-57-f9d911dce305>\", line 24, in clear\n",
      "    ImageGrab.grab((10,10,10,10)).save('user_input.jpg')\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\site-packages\\PIL\\Image.py\", line 2172, in save\n",
      "    save_handler(self, fp, filename)\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\site-packages\\PIL\\JpegImagePlugin.py\", line 784, in _save\n",
      "    ImageFile._save(im, fp, [(\"jpeg\", (0, 0) + im.size, 0, rawmode)], bufsize)\n",
      "  File \"C:\\Users\\hasan\\anaconda3\\lib\\site-packages\\PIL\\ImageFile.py\", line 527, in _save\n",
      "    e.setimage(im.im, b)\n",
      "SystemError: tile cannot extend outside image\n"
     ]
    }
   ],
   "source": [
    "width = 150  # canvas width\n",
    "height = 150 # canvas height\n",
    "center = height//2\n",
    "white = (255, 255, 255) # canvas back\n",
    "global x1,x2,y1,y2\n",
    "\n",
    "def save():\n",
    "    # save image to hard drive\n",
    "    filename = \"user_input.jpg\"\n",
    "    output_image.save(filename)\n",
    "\n",
    "\n",
    "\n",
    "def paint(event):\n",
    "    x1, y1 = (event.x - 1), (event.y - 1)\n",
    "    x2, y2 = (event.x + 1), (event.y + 1)\n",
    "    canvas.create_oval(x1, y1, x2, y2, fill=\"black\",width=5)\n",
    "    draw.line([x1, y1, x2, y2],fill=\"black\",width=5)\n",
    "\n",
    "    return x1,x2,y1,y2\n",
    "    \n",
    "def clear():\n",
    "    canvas.delete('all')\n",
    "    filename = \"user_input.jpg\"\n",
    "    output_image.save(filename)\n",
    "    #ImageGrab.grab((x1, y1, x1+x2, y1+y2)).save('user_input.jpg')\n",
    "\n",
    "master = Tk()\n",
    "\n",
    "# create a tkinter canvas to draw on\n",
    "canvas = Canvas(master, width=width, height=height, bg='white')\n",
    "canvas.pack()\n",
    "\n",
    "# create an empty PIL image and draw object to draw on\n",
    "output_image = PIL.Image.new(\"RGB\", (width, height), white)\n",
    "draw = ImageDraw.Draw(output_image)\n",
    "canvas.pack(expand=YES, fill=BOTH)\n",
    "canvas.bind(\"<B1-Motion>\", paint)\n",
    "\n",
    "# add a button to save the image\n",
    "button=Button(text=\"save\",command=save)\n",
    "clearButton = Button(text='clear', command=clear)\n",
    "\n",
    "button.pack()\n",
    "clearButton.pack()\n",
    "\n",
    "\n",
    "master.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6138890f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c9327a83",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
